# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 10:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_auto_20180327_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='\n            The JSON configuration. See section "Questionnaire\n            Configuration" of the manual for more information.<br/>\n            <strong>Hint</strong>: Use <a href="https://jqplay.org/">jq\n            play</a> to format your JSON.', null=True),
        ),
    ]
