# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0020_auto_20180322_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairetranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ru', 'Russian'), ('km', 'Khmer'), ('lo', 'Lao'), ('ar', 'Arabic'), ('pt', 'Portuguese'), ('af', 'Afrikaans'), ('th', 'Thai')], max_length=63),
        ),
    ]
