# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20170810_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentupdate',
            name='data',
        ),
    ]
