# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    """
    The previous migration removes the data field on the contentupdate table. This is by far
    the biggest table in the database - so call vacuum here to free up some space.
    """
    atomic = False

    dependencies = [
        ('notifications', '0007_remove_contentupdate_data'),
    ]

    operations = [
        migrations.RunSQL('vacuum full')
    ]
