# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-14 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20181011_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailpreferences',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ru', 'Russian'), ('zh', 'Chinese'), ('km', 'Khmer'), ('lo', 'Lao'), ('ar', 'Arabic'), ('pt', 'Portuguese'), ('af', 'Afrikaans'), ('th', 'Thai'), ('mn', 'Mongolian')], default='en', max_length=2),
        ),
    ]
